name: Deploy Release Asset to GitHub Pages
on:
  release:
    types: [published]
  workflow_dispatch:
permissions: read-all
jobs:
  add-release-asset:
    name: Add release asset
    runs-on: ubuntu-latest
    steps:
      - name: Add release asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          url=$(gh release view --json assets --jq '.assets[0].url')
          echo "<meta http-equiv='refresh' content='0;url=${url}'>" > index.html
      - name: Upload files as artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: .
  deploy:
    name: Deploy to GitHub Pages
    needs: add-release-asset
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5