name: Deploy Release Asset to GitHub Pages
on:
  release:
    types: [published]
  workflow_dispatch:
permissions: read-all
jobs:
  add-release-asset:
    name: Add release asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Add release asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir dist
          asset_url=$(gh release view --json assets --jq '.assets[0].url')
          asset_name=$(gh release view --json assets --jq '.assets[0].name')
          curl -L -H "Authorization: token ${GH_TOKEN}" -H "Accept: application/octet-stream" "${asset_url}" -o dist/${asset_name}
          echo "<meta http-equiv='refresh' content='0;url=${asset_name}'>" > dist/index.html
      - name: Upload files as artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: dist/
  deploy:
    name: Deploy to GitHub Pages
    needs: add-release-asset
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5